package com.ichaabane.ecommerce.dto.request;

import com.ichaabane.ecommerce.model.Address;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

/**
 * Payload for {@code POST /api/v1/customers}.
 *
 * <p>Deliberately carries no {@code id}: the identifier is generated by MongoDB,
 * never supplied by the client (mass-assignment protection).</p>
 */
public record CustomerCreateRequest(
    @NotBlank(message = "Customer firstname is required")
    String firstname,
    @NotBlank(message = "Customer lastname is required")
    String lastname,
    @NotBlank(message = "Customer Email is required")
    @Email(message = "Customer Email is not a valid email address")
    String email,
    Address address
) {

}
