server:
  port: 8090
spring:
  data:
    mongodb:
      username: ${MONGO_USER:ichaabane}
      password: ${MONGO_PASSWORD:ichaabane}
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: customer
      authentication-database: admin